### ISSUE TITLE
Nested elements with same name as root element overwrite root element's value.

### ISSUE THREAD

**Issue by paulpilone** [reaster/saxy#1]
When parsing XML with multi-elements if a nested element contains the same element as the root object the root object's property is overwritten with the child element's value. The following test fails:

``` objective-c
- (void)testDuplicateNestedAttributes
{
    NSString *xml = @"<tunes><tune><firstName>Daffy</firstName><lastName>Duck</lastName><child><firstName>Huey</firstName></child></tune></tunes>";

    //map 'tune' element to CartoonCharacter class:
    OXmlMapper *mapper = [[OXmlMapper mapper]
                          elements:@[
                          [OXmlElementMapper rootXPath:@"/tunes/tune" toMany:[CartoonCharacter class]]
                          ,
                          [[[OXmlElementMapper elementClass:[CartoonCharacter class]]
                            xpath:@"firstName" property:@"firstName"]
                           xpath:@"lastName" property:@"lastName"]
                          ]];

    OXmlReader *reader = [OXmlReader readerWithMapper:mapper];                      //creates a reader based on the mapper
    reader.context.logReaderStack = NO;                                             //'YES' -> log mapping process

    NSMutableArray *tunes = [reader readXmlText:xml];                               //reads xml
    CartoonCharacter *duck = tunes[0];
    STAssertEqualObjects(@"Daffy", duck.firstName,  @"mapped 'firstName' element to 'firstName' property");
}
```

This could just be an issue with how I define the xpath in the element mapping. I found that specifying 'tune/firstName' will fix the issue, but breaks if I need to write XML.

**Comment by reaster** [comment]
In general SAXy is a recursive stack-based mapper.  In the current design, it tries to match elements to properties on whatever object is currently on top of the stack.   There is a mechanism for ignoring properties, but not one for ignoring XML subtrees.  Ideally, there should be an ignore clause:

  ignoreXpath: @"child/firstName"]

or

  ignoreXpath: @"child/*"]

To follow what's going on at runtime, set:

  reader.context.logReaderStack = YES;

Now to the problem at hand.  If your object structure matches the XML (i.e. you have a child property):

@interface CartoonCharacter : NSObject
  @property(nonatomic)NSString *firstName;
  @property(nonatomic)NSString *lastName;
  @property(nonatomic)CartoonCharacter *child;
@end

SAXy will faithfully read and write your XML.  

If you wish to ignore nested properties with identical names, SAXy can still handle this if you're willing to get a little closer to the metal.  By overriding the getter and setter blocks of the unwanted xpath pattern with no-ops you can effectively ignore any value.  Try this:

```
                      [[[[OXmlElementMapper elementClass:[CartoonCharacter class]]
                        xpath:@"firstName" property:@"firstName"]
                       xpath:@"lastName" property:@"lastName"]
                      xpathMapper:[[[OXmlXPathMapper xpath:@"child/firstName" type:[NSString class]]
                                     setter:^(NSString *path, id name, id target, OXContext *ctx) {
                                     }]
                                    getter:^(NSString *path, id source, OXContext *ctx) {
                                        return (NSString *)nil;
                                    }]
                      ]
```

Hopefully, that will get you on to the next task...
