### ISSUE TITLE
saxy crash if you are trying to write first before read

### ISSUE THREAD

**Issue by axet** [reaster/saxy#2]
```

@interface CartoonCharacter : NSObject
@property(nonatomic, assign)BOOL  take;
@end

@implementation CartoonCharacter
@end

        CartoonCharacter *duck = [CartoonCharacter new];
        duck.take = TRUE;

        OXmlMapper *mapper = [[OXmlMapper mapper] elements:@[ [OXmlElementMapper rootXPath:@"/CartoonCharacter" type:[CartoonCharacter class]] ]];
        OXmlWriter *writer = [OXmlWriter writerWithMapper:mapper];

        NSLog(@"%@", [writer writeXml:duck prettyPrint:YES]);



```

**Comment by reaster** [comment]
Thanks for the bug report. It's fixed now, see OXmlWriterTests. As you may have figured out, BOOL types have to be manually mapped.

Regards,

Richard

@interface AssignOnly : NSObject
@property(nonatomic,assign)BOOL take;
@end

@implementation AssignOnly
@end

...
- (void)testWriteBeforeRead
  {
  AssignOnly *duck = [AssignOnly new];
  duck.take = TRUE;
  OXmlMapper *mapper = [[OXmlMapper mapper] elements:@[
                              [OXmlElementMapper rootXPath:@"/duck" type:[AssignOnly class]],
                              [[OXmlElementMapper elementClass:[AssignOnly class]]
                                                 tag:@"take" scalarType:OX_ENCODED_BOOL]
                        ]];
  OXmlWriter *writer = [OXmlWriter writerWithMapper:mapper];
  writer.xmlHeader = nil;
  
  NSString *xml = [writer writeXml:duck prettyPrint:NO];
  STAssertEqualObjects(@"<duck><take>true</take></duck>", xml,  @"write without first calling read");
  }
