### ISSUE TITLE
Converting a XML node to UIColor

### ISSUE THREAD

**Issue by sindilevich** [reaster/saxy#4]
Hello,

Trying to convert the next sample XML:

```
<appearance>
    <backgroundColor>#ff1122ee</backgroundColor>
</appearance>
```

to a class with UIColor backgroundColor class property: `@property (nonatomic, copy) UIColor* backgroundColor;` , fails with the following exception: **ERROR: missing required toTransform for NSString _->_ scalar mapping**.

This seems to be due the lack of transformer for UIColor's property `@property(nonatomic,readonly) CGColorRef CGColor;`.

Is there are a way to have SAXy parse _understand_ classes with UIColor properties?

**Comment by reaster** [comment]
The https://github.com/reaster/saxy/blob/master/SAXy/OX/OXTransform.h class defines the type conversion mechanisms and https://github.com/reaster/saxy/blob/master/SAXy/OX/OXTransform.m has lots of examples. You can use the following as a template for writing and registering the UIColor <-> NSString converters:

```
//NSURL <-> NSString
[self registerFrom:[NSString class] to:[NSURL class] transformer:^(id string, OXContext *ctx) {
    return [NSURL URLWithString:string];
}];
[self registerFrom:[NSURL class] to:[NSString class] transformer:^(id value, OXContext *ctx) {
    return [value absoluteString];
}];
```
